version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.5GB'
  
  api01:
    image: rinha-api
    hostname: rinha-api01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Timeout=5;Command Timeout=5;Pooling=true;Maximum Pool Size=750;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;Max Auto Prepare=100
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.5GB'
  
  api02:
    image: rinha-api
    hostname: rinha-api02
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Timeout=5;Command Timeout=5;Pooling=true;Maximum Pool Size=750;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;Max Auto Prepare=100
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.5GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.6GB'

networks:
  default:
    driver: bridge
    name: rinha